### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by cag014** [chriskuech/vs-code-viewer-extension#7]
Hi,
Your extension is very helpful, but on latest Edge release the code displayed in very small window....
Could you please take a look what went wrong?
![image](https://user-images.githubusercontent.com/45340622/102176930-1a822a80-3eab-11eb-9407-2dc6e7cdfe2b.png)

**Comment by pfeurean** [comment]
this should be fixed by #28. hopefully it will get worked into the process

**Comment by chriskuech** [comment]
Fix has been submitted for review by Microsoft and should be approved in <7 days.
